from win32com.client import Dispatch
import traceback

def TaskMonitor(func):

    def wrapper(*args,**kwargs):
        outlook = Dispatch('outlook.application')
        mail = outlook.CreateItem(0)
        # mail.To = 'data-analytics@phs.vn; namtran@phs.vn'
        mail.To = 'namtran@phs.vn'
        try:
            func(*args,**kwargs)
            mail.Subject = f"{func.__name__} Done"
            traceback_message = ''
        except (Exception,):
            mail.Subject = f"{func.__name__} Failed"
            traceback_message = traceback.format_exc()
        body = f"""
            <html>
                <head></head>
                <body>
                    <p style="font-family:Consolas; font-size:90%">
                    {traceback_message}
                    </p>
                    <p style="font-family:Times New Roman; font-size:90%"><i>
                        -- Generated by Reporting System
                    </i></p>
                </body>
            </html>
            """
        mail.HTMLBody = body
        mail.Send()

    return wrapper
